sudo: required
services:
  - docker

before_install:
  - docker build -t chakriMohamed/docker-react -f Dockerfile.dev .

script:
  - docker run ChakriMohamed/docker-react npm run test -- --coverage		 # coverage for exit and end the test
